# Generated by Django 2.0 on 2019-01-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('idArtista', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('pictureUrl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('idTag', models.IntegerField(primary_key=True, serialize=False)),
                ('tagValue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioArtista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idArtista', models.IntegerField()),
                ('idUsuario', models.IntegerField()),
                ('tiempoEscucha', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEtiquetaArtista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idArtista', models.IntegerField()),
                ('idUsuario', models.IntegerField()),
                ('idTag', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
