# Generated by Django 2.0 on 2019-01-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='numEpisodes',
            field=models.CharField(max_length=100),
        ),
    ]
