# Generated by Django 2.0 on 2018-12-10 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('title', models.CharField(max_length=40)),
                ('summary', models.TextField(max_length=500)),
                ('newsType', models.CharField(choices=[('Actualidad', 'Actualidad'), ('Deportes', 'Deportes'), ('Cultura', 'Cultura'), ('Política', 'Política'), ('Economía', 'Economía')], default='Actualidad', max_length=20)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.Diary')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('news', models.ManyToManyField(to='noticias.News')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='news',
            field=models.ManyToManyField(to='noticias.News'),
        ),
    ]
