# Generated by Django 2.0 on 2018-12-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='news',
            field=models.ManyToManyField(blank=True, to='noticias.News'),
        ),
        migrations.AlterField(
            model_name='user',
            name='news',
            field=models.ManyToManyField(blank=True, to='noticias.News'),
        ),
    ]
