# Generated by Django 2.0 on 2018-12-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20181210_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='news',
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ManyToManyField(to='noticias.Author'),
        ),
    ]
